name: Daily Joke
on:
  schedule:
    - cron: "* * * * *"
jobs:
  fetch-joke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install requests
        run: pip install requests
      - name: Fetch a joke
        run: |
          export DISPLAY=:0
          export XAUTHORITY=$HOME/.Xauthority
          import -window root -delay 200 screenshot.png
          import-im6.q16 -window root screenshot.png
          tesseract screenshot.png output
          cat output.txt
          rm screenshot.png output.txt
      - name: Commit and push changes
        run: |
          git config --global user.email "anand00rohan@gmail.com"
          git config --global user.name "rohan472000"
          git pull origin main
          git add README.md
          git commit -m "Add daily joke"
          git pull origin main
          git push origin main
