name: Daily Joke

on:
  schedule:
    - cron: "* * * * *"

jobs:
  fetch-joke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --user requests
      - name: Fetch a joke
        shell: python
        run: |
          import requests

          url = "https://v2.jokeapi.dev/joke/Any?type=single"

          response = requests.get(url)

          if response.status_code == 200:
              joke = response.json()["joke"]
              with open("README.md", "a") as readme_file:
                  readme_file.write(f"\n- {joke}")
          else:
              print("Failed to fetch joke")
      - name: Commit and push changes
        run: |
          git config --global user.email "anand00rohan@gmail.com"
          git config --global user.name "rohan anand"
          git add README.md
          git commit -m "Add daily joke"
          git push        
